using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace KS.RustAnalyzer.TestAdapter.Cargo;

/// <summary>
/// Strongly-typed models for cargo JSON output.
/// References:
/// - https://doc.rust-lang.org/cargo/reference/external-tools.html#json-messages
/// - https://doc.rust-lang.org/rustc/json.html
/// </summary>

#region Cargo Message Types

/// <summary>
/// Base cargo message - use <see cref="Reason"/> to determine the actual type.
/// </summary>
public class CargoMessage
{
    /// <summary>
    /// The type of message: "compiler-message", "compiler-artifact", "build-script-executed", "build-finished".
    /// </summary>
    [JsonProperty("reason")]
    public string Reason { get; set; }
}

/// <summary>
/// Cargo compiler message containing rustc diagnostics.
/// </summary>
public class CargoCompilerMessage : CargoMessage
{
    /// <summary>
    /// The Package ID specification.
    /// </summary>
    [JsonProperty("package_id")]
    public string PackageId { get; set; }

    /// <summary>
    /// Absolute path to the package manifest.
    /// </summary>
    [JsonProperty("manifest_path")]
    public string ManifestPath { get; set; }

    /// <summary>
    /// The Cargo target that generated the message.
    /// </summary>
    [JsonProperty("target")]
    public CargoTarget Target { get; set; }

    /// <summary>
    /// The rustc diagnostic message.
    /// </summary>
    [JsonProperty("message")]
    public RustcDiagnostic Message { get; set; }
}

/// <summary>
/// Cargo compiler artifact message.
/// </summary>
public class CargoCompilerArtifact : CargoMessage
{
    /// <summary>
    /// The Package ID specification.
    /// </summary>
    [JsonProperty("package_id")]
    public string PackageId { get; set; }

    /// <summary>
    /// Absolute path to the package manifest.
    /// </summary>
    [JsonProperty("manifest_path")]
    public string ManifestPath { get; set; }

    /// <summary>
    /// The Cargo target.
    /// </summary>
    [JsonProperty("target")]
    public CargoTarget Target { get; set; }

    /// <summary>
    /// The profile used for compilation.
    /// </summary>
    [JsonProperty("profile")]
    public CargoProfile Profile { get; set; }

    /// <summary>
    /// Array of features enabled.
    /// </summary>
    [JsonProperty("features")]
    public List<string> Features { get; set; }

    /// <summary>
    /// Array of files generated by this step.
    /// </summary>
    [JsonProperty("filenames")]
    public List<string> Filenames { get; set; }

    /// <summary>
    /// Path to the executable, or null if not applicable.
    /// </summary>
    [JsonProperty("executable")]
    public string Executable { get; set; }

    /// <summary>
    /// Whether the artifacts were already up-to-date (rustc was not run).
    /// </summary>
    [JsonProperty("fresh")]
    public bool Fresh { get; set; }
}

/// <summary>
/// Cargo build finished message.
/// </summary>
public class CargoBuildFinished : CargoMessage
{
    /// <summary>
    /// Whether the build finished successfully.
    /// </summary>
    [JsonProperty("success")]
    public bool Success { get; set; }
}

#endregion

#region Cargo Target and Profile

/// <summary>
/// Cargo target information.
/// </summary>
public class CargoTarget
{
    /// <summary>
    /// Array of target kinds (lib, bin, example, test, bench, custom-build).
    /// </summary>
    [JsonProperty("kind")]
    public List<string> Kind { get; set; }

    /// <summary>
    /// Array of crate types (lib, rlib, dylib, cdylib, staticlib, proc-macro, bin).
    /// </summary>
    [JsonProperty("crate_types")]
    public List<string> CrateTypes { get; set; }

    /// <summary>
    /// The name of the target.
    /// </summary>
    [JsonProperty("name")]
    public string Name { get; set; }

    /// <summary>
    /// Absolute path to the root source file of the target.
    /// </summary>
    [JsonProperty("src_path")]
    public string SrcPath { get; set; }

    /// <summary>
    /// The Rust edition of the target.
    /// </summary>
    [JsonProperty("edition")]
    public string Edition { get; set; }

    /// <summary>
    /// Whether the target should be documented.
    /// </summary>
    [JsonProperty("doc")]
    public bool Doc { get; set; }

    /// <summary>
    /// Whether doc tests are enabled.
    /// </summary>
    [JsonProperty("doctest")]
    public bool Doctest { get; set; }

    /// <summary>
    /// Whether tests are enabled.
    /// </summary>
    [JsonProperty("test")]
    public bool Test { get; set; }
}

/// <summary>
/// Cargo profile information.
/// </summary>
public class CargoProfile
{
    /// <summary>
    /// The optimization level.
    /// </summary>
    [JsonProperty("opt_level")]
    public string OptLevel { get; set; }

    /// <summary>
    /// The debug level (0, 1, 2, or string).
    /// </summary>
    [JsonProperty("debuginfo")]
    public object Debuginfo { get; set; }

    /// <summary>
    /// Whether debug assertions are enabled.
    /// </summary>
    [JsonProperty("debug_assertions")]
    public bool DebugAssertions { get; set; }

    /// <summary>
    /// Whether overflow checks are enabled.
    /// </summary>
    [JsonProperty("overflow_checks")]
    public bool OverflowChecks { get; set; }

    /// <summary>
    /// Whether the --test flag is used.
    /// </summary>
    [JsonProperty("test")]
    public bool Test { get; set; }
}

#endregion

#region Rustc Diagnostic Types

/// <summary>
/// Rustc diagnostic message.
/// See: https://doc.rust-lang.org/rustc/json.html
/// </summary>
public class RustcDiagnostic
{
    /// <summary>
    /// The primary diagnostic message.
    /// </summary>
    [JsonProperty("message")]
    public string Message { get; set; }

    /// <summary>
    /// The diagnostic code.
    /// </summary>
    [JsonProperty("code")]
    public DiagnosticCode Code { get; set; }

    /// <summary>
    /// The severity level: "error", "warning", "note", "help", "failure-note", "error: internal compiler error".
    /// </summary>
    [JsonProperty("level")]
    public string Level { get; set; }

    /// <summary>
    /// Array of source code spans related to this diagnostic.
    /// </summary>
    [JsonProperty("spans")]
    public List<DiagnosticSpan> Spans { get; set; }

    /// <summary>
    /// Array of child diagnostics (notes, help messages, etc.).
    /// </summary>
    [JsonProperty("children")]
    public List<RustcDiagnostic> Children { get; set; }

    /// <summary>
    /// The rendered diagnostic message as displayed by rustc.
    /// </summary>
    [JsonProperty("rendered")]
    public string Rendered { get; set; }
}

/// <summary>
/// Diagnostic code information.
/// </summary>
public class DiagnosticCode
{
    /// <summary>
    /// The unique diagnostic code (e.g., "E0001", "dead_code").
    /// </summary>
    [JsonProperty("code")]
    public string Code { get; set; }

    /// <summary>
    /// Optional explanation of the diagnostic.
    /// </summary>
    [JsonProperty("explanation")]
    public string Explanation { get; set; }
}

/// <summary>
/// Source code span for a diagnostic.
/// </summary>
public class DiagnosticSpan
{
    /// <summary>
    /// The file where the span is located.
    /// May be absolute or relative to the package root.
    /// </summary>
    [JsonProperty("file_name")]
    public string FileName { get; set; }

    /// <summary>
    /// Byte offset of the span start.
    /// </summary>
    [JsonProperty("byte_start")]
    public int ByteStart { get; set; }

    /// <summary>
    /// Byte offset of the span end.
    /// </summary>
    [JsonProperty("byte_end")]
    public int ByteEnd { get; set; }

    /// <summary>
    /// 1-based line number of the span start.
    /// </summary>
    [JsonProperty("line_start")]
    public int LineStart { get; set; }

    /// <summary>
    /// 1-based line number of the span end.
    /// </summary>
    [JsonProperty("line_end")]
    public int LineEnd { get; set; }

    /// <summary>
    /// 1-based column number of the span start.
    /// </summary>
    [JsonProperty("column_start")]
    public int ColumnStart { get; set; }

    /// <summary>
    /// 1-based column number of the span end.
    /// </summary>
    [JsonProperty("column_end")]
    public int ColumnEnd { get; set; }

    /// <summary>
    /// Whether this is the primary span (the main location of the diagnostic).
    /// </summary>
    [JsonProperty("is_primary")]
    public bool IsPrimary { get; set; }

    /// <summary>
    /// The source code text for this span.
    /// </summary>
    [JsonProperty("text")]
    public List<SpanText> Text { get; set; }

    /// <summary>
    /// Optional label describing the span.
    /// </summary>
    [JsonProperty("label")]
    public string Label { get; set; }

    /// <summary>
    /// Optional suggested replacement code.
    /// </summary>
    [JsonProperty("suggested_replacement")]
    public string SuggestedReplacement { get; set; }

    /// <summary>
    /// Confidence level of the suggestion: "MachineApplicable", "MaybeIncorrect", "HasPlaceholders", "Unspecified".
    /// </summary>
    [JsonProperty("suggestion_applicability")]
    public string SuggestionApplicability { get; set; }

    /// <summary>
    /// Optional macro expansion information.
    /// </summary>
    [JsonProperty("expansion")]
    public SpanExpansion Expansion { get; set; }
}

/// <summary>
/// Source code text within a span.
/// </summary>
public class SpanText
{
    /// <summary>
    /// The entire line of source code.
    /// </summary>
    [JsonProperty("text")]
    public string Text { get; set; }

    /// <summary>
    /// 1-based column where the highlight starts.
    /// </summary>
    [JsonProperty("highlight_start")]
    public int HighlightStart { get; set; }

    /// <summary>
    /// 1-based column where the highlight ends.
    /// </summary>
    [JsonProperty("highlight_end")]
    public int HighlightEnd { get; set; }
}

/// <summary>
/// Macro expansion information for a span.
/// </summary>
public class SpanExpansion
{
    /// <summary>
    /// The span where the macro was applied.
    /// </summary>
    [JsonProperty("span")]
    public DiagnosticSpan Span { get; set; }

    /// <summary>
    /// Name of the macro.
    /// </summary>
    [JsonProperty("macro_decl_name")]
    public string MacroDeclName { get; set; }

    /// <summary>
    /// Optional span where the macro is defined.
    /// </summary>
    [JsonProperty("def_site_span")]
    public DiagnosticSpan DefSiteSpan { get; set; }
}

#endregion
