<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RustAnalyzer.Remote\RustAnalyzer.Remote.csproj" />
    <ProjectReference Include="..\RustAnalyzer.TestAdapter\RustAnalyzer.TestAdapter.csproj" />
  </ItemGroup>

  <Import Project="..\KS.Tests.Common.targets" />

</Project>
