<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\TestsCommon\RaVsDiffReporter.cs" Link="Common\RaVsDiffReporter.cs" />
    <Compile Include="..\TestsCommon\TestHelpers.cs" Link="Common\TestHelpers.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.VisualStudio.TestWindow.Interfaces">
      <HintPath>..\external\vs.17.11\Microsoft.VisualStudio.TestWindow.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualStudio.Workspace">
      <HintPath>..\external\vs.17.11\Microsoft.VisualStudio.Workspace.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualStudio.Workspace.Extensions">
      <HintPath>..\external\vs.17.11\Microsoft.VisualStudio.Workspace.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualStudio.Workspace.Extensions.VS">
      <HintPath>..\external\vs.17.11\Microsoft.VisualStudio.Workspace.Extensions.VS.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualStudio.Workspace.VSIntegration">
      <HintPath>..\external\vs.17.11\Microsoft.VisualStudio.Workspace.VSIntegration.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualStudio.Workspace.VSIntegration.Contracts">
      <HintPath>..\external\vs.17.11\Microsoft.VisualStudio.Workspace.VSIntegration.Contracts.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RustAnalyzer.TestAdapter\RustAnalyzer.TestAdapter.csproj" />
    <ProjectReference Include="..\RustAnalyzer\RustAnalyzer.csproj" />
  </ItemGroup>

  <Target Name="CopyTestProjects" AfterTargets="Build">
    <ItemGroup>
      <TestProjectsFiles Include="..\TestProjects\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(TestProjectsFiles)" DestinationFolder="$(TargetDir)\Cargo\TestData\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>

  <Import Project="..\KS.Tests.Common.targets" />

</Project>
