<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\RustAnalyzer\source.extension.cs" Link="source.extension.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RustAnalyzer.TestAdapter\RustAnalyzer.TestAdapter.csproj" />
  </ItemGroup>

  <Import Project="..\KS.Common.targets" />

</Project>
