<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\TestsCommon\RaVsDiffReporter.cs" Link="Common\RaVsDiffReporter.cs" />
    <Compile Include="..\TestsCommon\TestHelpers.cs" Link="Common\TestHelpers.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Cargo\TestData\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RustAnalyzer.TestAdapter\RustAnalyzer.TestAdapter.csproj" />
  </ItemGroup>

  <Target Name="CopyTestProjects" AfterTargets="Build">
    <ItemGroup>
      <TestProjectsFiles Include="..\TestProjects\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(TestProjectsFiles)" DestinationFolder="$(TargetDir)\Cargo\TestData\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>

  <Import Project="..\KS.Tests.Common.targets" />

</Project>
